# See https://wiki.hyprland.org/Configuring/Monitors/
# List current monitors and resolutions possible: hyprctl monitors

# Default: auto-detect all monitors
monitorv2 {
    output = 
    mode = preferred
    position = auto
    scale = auto
}

# Optimized for retina-class 2x displays, like 13" 2.8K, 27" 5K, 32" 6K.
# env = GDK_SCALE, 2
# monitorv2 {
#     output = 
#     mode = preferred
#     position = auto
#     scale = 2
# }

# Good compromise for 27" or 32" 4K monitors (but fractional!)
# env = GDK_SCALE, 1.75
# monitorv2 {
#     output = 
#     mode = preferred
#     position = auto
#     scale = 1.6
# }

# Intel MacBook Retina (13" 2560x1600)
# env = GDK_SCALE, 1.25
# monitorv2 {
#     output = eDP-1
#     mode = 2560x1600@60
#     position = auto
#     scale = 1.33
# }

# Portrait/rotated secondary monitor
# monitorv2 {
#     output = DP-2
#     mode = preferred
#     position = auto
#     scale = 1
#     transform = 1
# }

# Example for Framework 13 w/ 6K XDR Apple display
# monitorv2 {
#     output = DP-5
#     mode = 6016x3384@60
#     position = auto
#     scale = 2
# }
# monitorv2 {
#     output = eDP-1
#     mode = 2880x1920@120
#     position = auto
#     scale = 2
# }
