#!/bin/bash

sudo pacman -S --noconfirm --needed \
  alacritty \
  asdcontrol-git \
  avahi \
  bash-completion \
  bat \
  blueberry \
  brightnessctl \
  btop \
  cargo \
  clang \
  clipmenu \
  cmake \
  cups \
  cups-browsed \
  cups-filters \
  cups-pdf \
  dmenu \
  docker \
  docker-buildx \
  docker-compose \
  dust \
  evince \
  eza \
  fastfetch \
  fcitx5 \
  fcitx5-gtk \
  fcitx5-qt \
  fd \
  ffmpegthumbnailer \
  fontconfig \
  firefox \
  firefoxpwa \
  fzf \
  gcc14 \
  gdb \
  github-cli \
  gnome-themes-extra \
  gnupg \
  gum \
  gvfs-mtp \
  gvfs-smb \
  hypridle \
  hyprland \
  hyprland-qtutils \
  hyprlock \
  hyprpicker \
  hyprshot \
  hyprsunset \
  imagemagick \
  impala \
  imv \
  inetutils \
  iwd \
  jq \
  kdenlive \
  kvantum-qt5 \
  lazydocker \
  lazygit \
  less \
  libqalculate \
  llvm \
  localsend \
  luarocks \
  mako \
  man \
  mise \
  mpv \
  nautilus \
  noto-fonts \
  noto-fonts-cjk \
  noto-fonts-emoji \
  noto-fonts-extra \
  nss-mdns \
  nvim \
  pamixer \
  pinta \
  playerctl \
  plocate \
  plymouth \
  polkit-gnome \
  power-profiles-daemon \
  python-gobject \
  python-lxml \
  python-pip \
  python-poetry-core \
  python-pykeepass \
  python-terminaltexteffects \
  qt5-wayland \
  ripgrep \
  satty \
  signal-desktop \
  slurp \
  socat \
  speedtest-cli \
  spotify \
  starship \
  sushi \
  swaybg \
  swayosd \
  system-config-printer \
  thunderbird \
  tldr \
  tree-sitter-cli \
  ttf-cascadia-mono-nerd \
  ttf-ia-writer \
  ttf-jetbrains-mono-nerd \
  tzupdate \
  ufw \
  ufw-docker \
  unzip \
  uwsm \
  visual-studio-code-bin \
  walker-bin \
  waybar \
  websocat \
  wf-recorder \
  whois \
  wireless-regdb \
  wiremix \
  wireplumber \
  wl-clip-persist \
  wl-clipboard \
  wl-screenrec \
  woff2-font-awesome \
  wtype \
  xdg-desktop-portal-gtk \
  xdg-desktop-portal-hyprland \
  xmlstarlet \
  yaru-icon-theme \
  yay \
  ydotool \
  zoxide

yay -S --noconfirm --needed \
  hyprmon-bin \
  keepmenu \
  pinentry-rofi \
  python-pynput
